name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CONFIG_PATH: ./config/testing.yaml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod download

      - name: Build application
        run: go build -o myapp ./cmd

      - name: Start migration
        run: go run ./cmd/migrator --storage-path=./database/users.db --migrations-path=./database/migrations

      - name: Start application
        run: ./myapp &

      - name: Wait for application to start
        run: sleep 10

      - name: Run tests
        run: go test ./...
